cras: Include the panic message in crash reports
BUG=b:410986360
TEST=CRAS_RUST_PANIC_FOR_TESTING=1 cras-dev.sh
TEST=grep "sig=panicked at 'panicing due to CRAS_RUST_PANIC_FOR_TESTING'" /var/spool/crash/cras.*.meta

Cq-Depend: chromium:6461145
Change-Id: I442532c0376a5d21d3d9d9bf0743fead248de4d8
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/6458258
Reviewed-by: Judy Hsiao <judyhsiao@google.com>
Tested-by: chromeos-cop-builder@chromeos-cop.iam.gserviceaccount.com <chromeos-cop-builder@chromeos-cop.iam.gserviceaccount.com>
Commit-Queue: Li-Yu Yu <aaronyu@google.com>