sof_tests: cstate command for queryimg comp states
Supports command "cstate" to get the current state ("on"/"off") of the
given SOF component type, or signal "exists" at least while unable to
resolve the state. Usage:

sof_tests cstate [COMPONENT] [--expect]

  COMPONENT - The component type with possible values:
              [nc, aec, drc, eq, waves, dts, dsm, ghd], or ask for
              scanning all components by leaving it non-specified.
  -e , --expect - Print state only if it's expected to exist.

BUG=b:339975492
TEST=run commands below on SOF-backed CrOS devices, e.g. anahera
1. cmd#> sof_tests cstate
list all available components:
 + NC     is ON ; detected card0 CTL numid=52,name='RTNR10.0 rtnr_enable_10'
 - AEC    is off; detected card0 CTL numid=49,name='GOOGLE_RTC_AUDIO_PROCESSING10.0 Config'
2. cmd#> sof_tests cstate nc
 + NC     is ON ; detected card0 CTL numid=52,name='RTNR10.0 rtnr_enable_10'
3. cmd#> sof_tests cstate dts
DTS doesn't exist
4. cmd#> sof_tests cstate aec -e
Off
5. cmd#> sof_tests cstate eq -e
ERROR: cmd cstate: no control is detected

Change-Id: I772b2694514c821c5b0fe79f16350704ca1cdf3c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/5628571
Tested-by: chromeos-cop-builder@chromeos-cop.iam.gserviceaccount.com <chromeos-cop-builder@chromeos-cop.iam.gserviceaccount.com>
Auto-Submit: Pin-chih Lin <johnylin@google.com>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Commit-Queue: Pin-chih Lin <johnylin@google.com>