pkg_config: Fix hdrs globs usage
Library headers live under "{library_root}{path}" instead of "library".

This will cause library depends on "@pkg_config//:dbus-1" fail with

```
fatal error: #include <dbus/dbus.h>: No such file or directory
```

BUG=b:251701189
TEST=bazel build //...

Change-Id: Idb676f8fd13c938a4c7ddf19508afae87bc9746f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/3934675
Reviewed-by: Li-Yu Yu <aaronyu@google.com>
Commit-Queue: Chih-Yang Hsia <paulhsia@chromium.org>
Auto-Submit: Chih-Yang Hsia <paulhsia@chromium.org>
Tested-by: Chih-Yang Hsia <paulhsia@chromium.org>