CRAS: fix ewam_power unittest
undefined reference to symbol 'pthread_getspecific@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols:
DSO missing from command line

BUG=b:192453217
TEST=make check -j64

Change-Id: Ib4b9c86ab3fcb1582b1ed0f2a51528d4191975e2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/2997391
Auto-Submit: En-Shuo Hsu <enshuo@chromium.org>
Reviewed-by: Chih-Yang Hsia <paulhsia@chromium.org>
Commit-Queue: En-Shuo Hsu <enshuo@chromium.org>
Tested-by: En-Shuo Hsu <enshuo@chromium.org>