cras: Use full path includes
Apply fix_includes.py then format.
https://gist.github.com/afq984/1df3281804c20ec0df3776dff35ec11b

There are other changes needed because gcc appears to be more strict
when a header is included with its full path (x/y/z.h) instead of with
its basename (z.h):

Drop const from sample_buffer::sample_size.
> In file included from cras/src/tests/sr_stub.cc:10:
> ./cras/src/common/sample_buffer.h: In function 'int sample_buffer_init(size_t, size_t, sample_buffer*)':
> ./cras/src/common/sample_buffer.h:67:15: error: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct sample_buffer' with no trivial copy-assignment; use copy-initialization instead [-Werror=class-memaccess]
>    67 |         memcpy(buf, &temp_buf, sizeof(struct sample_buffer));
>       |         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./cras/src/common/sample_buffer.h:34:8: note: 'struct sample_buffer' declared here
>    34 | struct sample_buffer {
>       |        ^~~~~~~~~~~~~

Also there are a lot of -Wsign-compare errors showing up again.
Disable them for now.

BUG=b:257924473
TEST=audio-qv

Change-Id: I410b92f33df4550d10a9be4b7846cf877909b691
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/4242302
Tested-by: Audio Quick Verifier <audio-qv@chromeos-audio-qv.iam.gserviceaccount.com>
Reviewed-by: Chih-Yang Hsia <paulhsia@chromium.org>
Commit-Queue: Li-Yu Yu <aaronyu@google.com>