cras_dsp_mod_builtin: Remove unused variable
error: variable ‘ports’ set but not used [-Werror=unused-but-set-variable]
  173 |  float **ports;
      |          ^~~~~

BUG=b:172342238
TEST=make

Change-Id: Ic7a14362cee2d3e0c9bfee8f6a3f19509b6366bb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/2859403
Reviewed-by: Chih-Yang Hsia <paulhsia@chromium.org>
Reviewed-by: Cheng-Yi Chiang <cychiang@chromium.org>
Tested-by: Chih-Yang Hsia <paulhsia@chromium.org>
Commit-Queue: Chih-Yang Hsia <paulhsia@chromium.org>