CRAS: Use C version stubs for `cras` build
Using tests/{sr_stub.cc, sr_bt_util_stub.cc} causes
```
undefined reference to `vtable for __cxxabiv1::__function_type_info'
```
failures in `undefined` oss-fuzz build.

Those files force cras needs to be built with `-llibstdc++` but it's
unnecessary.

Replace those usage with C version stub files.

BUG=b:216075565
TEST=git clone https://github.com/google/oss-fuzz.git && \
  cd oss-fuzz && \
  python3 infra/helper.py build_fuzzers --clean \
  --sanitizer undefined cras \
  /path/to/cras

Change-Id: I946ab2cfc55e2f63c010d9c78cf7630eff5becbc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/3782691
Reviewed-by: Li-Yu Yu <aaronyu@google.com>
Commit-Queue: Li-Yu Yu <aaronyu@google.com>
Auto-Submit: Chih-Yang Hsia <paulhsia@chromium.org>
Tested-by: Chih-Yang Hsia <paulhsia@chromium.org>