CRAS: Add MAX_ALSA_CARD_NAME_LENGTH
We introduced MAX_ALSA_PCM_NAME_LENGTH in 7e4ca79 and override its
meaning without keeping the length limit for card's name. As we share
the length definition for alsa card and alsa pcm. GCC raises a
format-truncation error on the line of filling pcm_name.

server/cras_alsa_card.c:108:51: error: ‘%u’ directive output may be
truncated writing between 1 and 10 bytes into a region of size between
0 and 8 [-Werror=format-truncation=]
snprintf(pcm_name, MAX_ALSA_PCM_NAME_LENGTH, "%s,%u", alsa_card->name,
                                                 ^~
         device_index);

BUG=None
TEST=Compile

Change-Id: I92562a463ec647f4fc0eafcdc3ef537ad07527fb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/2237625
Commit-Queue: En-Shuo Hsu <enshuo@chromium.org>
Tested-by: En-Shuo Hsu <enshuo@chromium.org>
Reviewed-by: Hsinyu Chao <hychao@chromium.org>