CRAS: fix non-critical build error due to missing oom score
When building cras, the following (non-critical) error is shown:

ERROR: Missing clauses from upstart script
"/build/${BOARD}/tmp/portage/media-sound/${BOARD}-9999/image/etc/init/cras.conf": oom
Please see:
https://dev.chromium.org/chromium-os/chromiumos-design-docs/boot-design#TOC-Runtime-Resource-Limits

, and we suggest setting the oom score per the requirement to suppress the error message.

https://www.chromium.org/chromium-os/chromiumos-design-docs/out-of-memory-handling/
advises that "CrOS daemons that can recover", which is the closest
description to our situation, should go with -100 score.

Note that the default (when not setting) goes with -1000, which may be
rather inappropriate.

BUG=None
TEST=FEATURES=test USE=asan emerge-${BOARD} adhd

Change-Id: I52d7a167f0c1a9fc8ea52511ab88c6adf3b73bd3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/3573824
Reviewed-by: Li-Yu Yu <aaronyu@google.com>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Commit-Queue: Jeremy Wu <jrwu@google.com>
Tested-by: Jeremy Wu <jrwu@google.com>