CRAS: cras_hfp_info: Fix gcc build error
While building with gcc we got error

```
../../src/server/cras_hfp_info.c: In function ‘hfp_read_msbc’:
../../src/server/cras_hfp_info.c:414:2: error: variable-sized object may not be initialized
  414 |  char control[control_size] = { 0 };
      |  ^~~~
../../src/server/cras_hfp_info.c:414:33: error: excess elements in array initializer [-Werror]
  414 |  char control[control_size] = { 0 };
      |                                 ^
```

We need to initialized dynamic array with memset.

BUG=None
TEST='./configure && make check'

Change-Id: I09fcf91d3fd749f7cbb3aab87b805ef7a6a3f6ed
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/2329346
Tested-by: Chih-Yang Hsia <paulhsia@chromium.org>
Reviewed-by: Hsinyu Chao <hychao@chromium.org>
Reviewed-by: Dylan Reid <dgreid@chromium.org>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Commit-Queue: Chih-Yang Hsia <paulhsia@chromium.org>