libcras: Use addr_of_mut! while resolving unaligned address
For a packed struct P. Using `&mut p.field2 as *mut _` is an undefined
behavior since the code needs to reference the unaligned struct first.
And will generate error like this:

error[E0793]: reference to packed field is unaligned
   --> libcras/src/cras_shm.rs:87:26
87  |         VolatileRef::new(&mut $addr.as_mut().$($field).* as *mut _)
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
123 |                 used_size: vref_from_addr!(addr, config.used_size),
    |                            --------------------------------------- in this macro invocation

Therefore, we change to use addr_of_mut! in the vref_from_addr! macro instead.

Changes:
- Use addr_of_mut! in vref_from_addr! macro
- Remove #![warn(unaligned_references)]
- Move remaining TODOs to vref_from_addr! comments

BUG=b:239850356
BUG=b:283969454
TEST=cargo test

Change-Id: I1730149cc8618aa8c665d85af0b95a4ef109abbe
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/4573014
Commit-Queue: Chih-Yang Hsia <paulhsia@chromium.org>
Reviewed-by: Li-Yu Yu <aaronyu@google.com>
Tested-by: Chih-Yang Hsia <paulhsia@chromium.org>
Tested-by: ChromeOS Audio Quick Verifier <audio-qv@chromeos-audio-qv.iam.gserviceaccount.com>