CRAS: Fix alsa_io_unittest
Remove unused variable and fix uninitialized variable.

tests/alsa_io_unittest.cc: In member function ‘virtual void {anonymous}::
AlsaIoInit_QuadChannelInternalSpeakerOpenPlayback_Test::TestBody()’:
tests/alsa_io_unittest.cc:425:19: error: variable ‘aio’ set but not used
[-Werror=unused-but-set-variable]
  425 |   struct alsa_io* aio;
      |                   ^~~

tests/alsa_io_unittest.cc: In member function ‘virtual void {anonymous}::
AlsaIoInit_OpenCaptureSetCaptureGainWithDefaultNodeGain_Test::TestBody()’:
tests/alsa_io_unittest.cc:2895:9: error: ‘format’ may be used
uninitialized in this function [-Werror=maybe-uninitialized]
 2895 |   memcpy(fake_format, fmt, sizeof(cras_audio_format));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

BUG=b:192453217
TEST=make check -j64

Change-Id: I30da307f23099aafeba1943913810fe452b32de0
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/2997388
Reviewed-by: Chih-Yang Hsia <paulhsia@chromium.org>
Commit-Queue: Chih-Yang Hsia <paulhsia@chromium.org>
Tested-by: Chih-Yang Hsia <paulhsia@chromium.org>